"$nc_tools_path/Fixtures"
"$nc_tools_path/Fixtures/123-blocks"
"$nc_tools_path/Fixtures/angle-irons"
"$nc_tools_path/Fixtures/angle-irons/from ptc"
"$nc_tools_path/Fixtures/assemblies"
"$nc_tools_path/Fixtures/Centers"
"$nc_tools_path/Fixtures/Centers/Dead Center"
"$nc_tools_path/Fixtures/Centers/Live Center"
"$nc_tools_path/Fixtures/chucks"
"$nc_tools_path/Fixtures/chucks/from ptc"
"$nc_tools_path/Fixtures/clamps"
"$nc_tools_path/Fixtures/clamps/from ptc"
"$nc_tools_path/Fixtures/clamps/Step-Block Hold-Down Set"
"$nc_tools_path/Fixtures/knobs"
"$nc_tools_path/Fixtures/parallels"
"$nc_tools_path/Fixtures/plates"
"$nc_tools_path/Fixtures/plates/faceplates"
"$nc_tools_path/Fixtures/plates/from ptc"
"$nc_tools_path/Fixtures/vblocks"
"$nc_tools_path/Fixtures/Vise"
"$nc_tools_path/Fixtures/Vise/5-axis-multi"
"$nc_tools_path/Fixtures/Vise/small-vise"
"$nc_tools_path/Hardware"
"$nc_tools_path/Hardware/flat-head-hex-screws"
"$nc_tools_path/Hardware/hex-nuts"
"$nc_tools_path/Hardware/socket-head-cap-screws"
"$nc_tools_path/Hardware/standoffs"
"$nc_tools_path/Hardware/washers"
"$nc_tools_path/Misc"
"$nc_tools_path/Parameters"
"$nc_tools_path/Sequences"
"$nc_tools_path/Sites Files"
"$nc_tools_path/Solid Tools"
"$nc_tools_path/Solid Tools/holder_lib"
"$nc_tools_path/Solid Tools/holder_lib/bt_flange"
"$nc_tools_path/Solid Tools/holder_lib/bt_flange/collet_chuck_b"
"$nc_tools_path/Solid Tools/holder_lib/bt_flange/col_tap_chuck_b"
"$nc_tools_path/Solid Tools/holder_lib/bt_flange/endmill_b"
"$nc_tools_path/Solid Tools/holder_lib/bt_flange/morse_taper_b"
"$nc_tools_path/Solid Tools/holder_lib/morse_taper"
"$nc_tools_path/Solid Tools/holder_lib/qc_flange"
"$nc_tools_path/Solid Tools/holder_lib/qc_flange/collet_chuck_q"
"$nc_tools_path/Solid Tools/holder_lib/qc_flange/col_tap_chuck_q"
"$nc_tools_path/Solid Tools/holder_lib/qc_flange/endmill_q"
"$nc_tools_path/Solid Tools/holder_lib/qc_flange/float_holder_q"
"$nc_tools_path/Solid Tools/holder_lib/qc_flange/morse_taper_q"
"$nc_tools_path/Solid Tools/holder_lib/str_shank"
"$nc_tools_path/Solid Tools/holder_lib/str_shank/collet_chuck_s"
"$nc_tools_path/Solid Tools/holder_lib/str_shank/col_tap_chuck_s"
"$nc_tools_path/Solid Tools/holder_lib/str_shank/float_holder_s"
"$nc_tools_path/Solid Tools/holder_lib/str_shank/float_holder_s/double_pin_s"
"$nc_tools_path/Solid Tools/holder_lib/str_shank/float_holder_s/full_float_s"
"$nc_tools_path/Solid Tools/holder_lib/str_shank/float_holder_s/roller_drive_s"
"$nc_tools_path/Solid Tools/holder_lib/tapping_systems"
"$nc_tools_path/Solid Tools/holder_lib/tapping_systems/reversing_t"
"$nc_tools_path/Solid Tools/holder_lib/tapping_systems/reversing_t/assembly_tr"
"$nc_tools_path/Solid Tools/holder_lib/tapping_systems/reversing_t/assembly_tr/bt_flange_tra"
"$nc_tools_path/Solid Tools/holder_lib/tapping_systems/reversing_t/assembly_tr/v_flange_tra"
"$nc_tools_path/Solid Tools/holder_lib/tapping_systems/reversing_t/tap_chuck_tr"
"$nc_tools_path/Solid Tools/holder_lib/tapping_systems/safe_drive_t"
"$nc_tools_path/Solid Tools/holder_lib/tapping_systems/safe_drive_t/qc_flange_td"
"$nc_tools_path/Solid Tools/holder_lib/tapping_systems/safe_drive_t/v_flange_td"
"$nc_tools_path/Solid Tools/holder_lib/tapping_systems/self_releasing_t"
"$nc_tools_path/Solid Tools/holder_lib/tapping_systems/self_releasing_t/assembly_ts"
"$nc_tools_path/Solid Tools/holder_lib/tapping_systems/self_releasing_t/assembly_ts/bt_flange_tsa"
"$nc_tools_path/Solid Tools/holder_lib/tapping_systems/self_releasing_t/assembly_ts/v_flange_tsa"
"$nc_tools_path/Solid Tools/holder_lib/tapping_systems/self_releasing_t/tap_chuck_ts"
"$nc_tools_path/Solid Tools/holder_lib/tapping_systems/shank_adapt_t"
"$nc_tools_path/Solid Tools/holder_lib/tapping_systems/solid_drive_t"
"$nc_tools_path/Solid Tools/holder_lib/v_flange"
"$nc_tools_path/Solid Tools/holder_lib/v_flange/collet_chuck_v"
"$nc_tools_path/Solid Tools/holder_lib/v_flange/col_tap_chuck_v"
"$nc_tools_path/Solid Tools/holder_lib/v_flange/endmill_v"
"$nc_tools_path/Solid Tools/holder_lib/v_flange/float_holder_v"
"$nc_tools_path/Solid Tools/holder_lib/v_flange/morse_taper_v"
"$nc_tools_path/Solid Tools/holder_lib/v_flange/str_shank_v"
"$nc_tools_path/Solid Tools/Tools"
"$nc_tools_path/Solid Tools/Tools/ball endmills"
"$nc_tools_path/Solid Tools/Tools/bull endmills"
"$nc_tools_path/Solid Tools/Tools/center drills"
"$nc_tools_path/Solid Tools/Tools/chamfering"
"$nc_tools_path/Solid Tools/Tools/drills-inch"
"$nc_tools_path/Solid Tools/Tools/endmills"
"$nc_tools_path/Solid Tools/Tools/facemills"
"$nc_tools_path/Solid Tools/Tools/flycutter"
"$nc_tools_path/Solid Tools/Tools/gear-hobs"
"$nc_tools_path/Solid Tools/Tools/isotools"
"$nc_tools_path/Solid Tools/Tools/isotools/isodrills"
"$nc_tools_path/Solid Tools/Tools/isotools/isomills"
"$nc_tools_path/Solid Tools/Tools/isotools/isoreamers"
"$nc_tools_path/Solid Tools/Tools/isotools/isotaps"
"$nc_tools_path/Solid Tools/Tools/kennametal"
"$nc_tools_path/Solid Tools/Tools/lost and found"
"$nc_tools_path/Solid Tools/Tools/metric_t"
"$nc_tools_path/Solid Tools/Tools/metric_t/drills_m"
"$nc_tools_path/Solid Tools/Tools/metric_t/taps_m"
"$nc_tools_path/Solid Tools/Tools/probes"
"$nc_tools_path/Solid Tools/Tools/side mills"
"$nc_tools_path/Solid Tools/Tools/standard_t"
"$nc_tools_path/Solid Tools/Tools/standard_t/drills_s"
"$nc_tools_path/Solid Tools/Tools/standard_t/mills_s"
"$nc_tools_path/Solid Tools/Tools/standard_t/reamers_s"
"$nc_tools_path/Solid Tools/Tools/standard_t/taps_s"
"$nc_tools_path/Solid Tools/Tools/standard_t/turn_s"
"$nc_tools_path/Solid Tools/Tools/standard_t/turn_s/either_hand"
"$nc_tools_path/Solid Tools/Tools/standard_t/turn_s/left_hand"
"$nc_tools_path/Solid Tools/Tools/standard_t/turn_s/right_hand"
"$nc_tools_path/Solid Tools/Tools/tapping"
"$nc_tools_path/Solid Tools/Tools/turning"
"$nc_tools_path/Solid Tools/Tools/turning/either_hand"
"$nc_tools_path/Solid Tools/Tools/turning/grooving"
"$nc_tools_path/Solid Tools/Tools/turning/lefthand"
"$nc_tools_path/Solid Tools/Tools/turning/righthand"
"$nc_tools_path/Start_Templates"
"$nc_tools_path/Tools"
"$nc_tools_path/Tools/inch"
"$nc_tools_path/Tools/inch/drilling"
"$nc_tools_path/Tools/inch/drilling/back-spot-facing-inch"
"$nc_tools_path/Tools/inch/drilling/boring-bars-inch"
"$nc_tools_path/Tools/inch/drilling/center-drills-inch"
"$nc_tools_path/Tools/inch/drilling/countersinks-inch"
"$nc_tools_path/Tools/inch/drilling/drills-inch"
"$nc_tools_path/Tools/inch/drilling/drills-inch/decimal"
"$nc_tools_path/Tools/inch/drilling/drills-inch/decimal/large"
"$nc_tools_path/Tools/inch/drilling/drills-inch/decimal/medium"
"$nc_tools_path/Tools/inch/drilling/drills-inch/decimal/small"
"$nc_tools_path/Tools/inch/drilling/drills-inch/fractional"
"$nc_tools_path/Tools/inch/drilling/drills-inch/letter"
"$nc_tools_path/Tools/inch/drilling/drills-inch/number"
"$nc_tools_path/Tools/inch/drilling/drills-inch/tap_drills"
"$nc_tools_path/Tools/inch/drilling/multi-tips-inch"
"$nc_tools_path/Tools/inch/drilling/reamers-inch"
"$nc_tools_path/Tools/inch/drilling/reamers-inch/oversized"
"$nc_tools_path/Tools/inch/drilling/reamers-inch/undersized"
"$nc_tools_path/Tools/inch/drilling/spot-drills-inch"
"$nc_tools_path/Tools/inch/drilling/taps-inch"
"$nc_tools_path/Tools/inch/milling"
"$nc_tools_path/Tools/inch/milling/ball-endmills-inch"
"$nc_tools_path/Tools/inch/milling/barrel-lens-mills-inch"
"$nc_tools_path/Tools/inch/milling/barrel-tangent-mills-inch"
"$nc_tools_path/Tools/inch/milling/barrel-taper-mills-inch"
"$nc_tools_path/Tools/inch/milling/bull-endmills-inch"
"$nc_tools_path/Tools/inch/milling/chamfer-mills-inch"
"$nc_tools_path/Tools/inch/milling/corner-round-mills-inch"
"$nc_tools_path/Tools/inch/milling/endmills-inch"
"$nc_tools_path/Tools/inch/milling/endmills-inch/solid"
"$nc_tools_path/Tools/inch/milling/engraving-tools"
"$nc_tools_path/Tools/inch/milling/facemills-inch"
"$nc_tools_path/Tools/inch/milling/groove-mills-inch"
"$nc_tools_path/Tools/inch/milling/key-mills-inch"
"$nc_tools_path/Tools/inch/milling/lollipop-mills-inch"
"$nc_tools_path/Tools/inch/milling/mills-inch"
"$nc_tools_path/Tools/inch/milling/plunge-mills-inch"
"$nc_tools_path/Tools/inch/milling/side-mill-inch"
"$nc_tools_path/Tools/inch/milling/sketched-tools-inch"
"$nc_tools_path/Tools/inch/milling/sketched-tools-inch/report"
"$nc_tools_path/Tools/inch/milling/sketched-tools-inch/report/FACING"
"$nc_tools_path/Tools/inch/milling/sketched-tools-inch/report/FACING/image_mfg"
"$nc_tools_path/Tools/inch/milling/sketched-tools-inch/report/FACING/image_step"
"$nc_tools_path/Tools/inch/milling/sketched-tools-inch/report/FACING/image_tool"
"$nc_tools_path/Tools/inch/milling/sketched-tools-inch/report/MFG0001"
"$nc_tools_path/Tools/inch/milling/sketched-tools-inch/report/MFG0001/image_mfg"
"$nc_tools_path/Tools/inch/milling/sketched-tools-inch/report/MFG0001/image_step"
"$nc_tools_path/Tools/inch/milling/sketched-tools-inch/report/MFG0001/image_tool"
"$nc_tools_path/Tools/inch/milling/slitting-saws-inch"
"$nc_tools_path/Tools/inch/milling/taper-ball-endmills-inch"
"$nc_tools_path/Tools/inch/milling/taper-endmills-inch"
"$nc_tools_path/Tools/inch/milling/thread-mills-inch"
"$nc_tools_path/Tools/inch/turning"
"$nc_tools_path/Tools/inch/turning/grooving"
"$nc_tools_path/Tools/inch/turning/turning_tools"
"$nc_tools_path/Tools/inch/wire-edm"
"$nc_tools_path/Tools/metric"
"$nc_tools_path/Tools/metric/milling"
"$nc_tools_path/Tools/metric/milling/ball-endmills-metric"
"$nc_tools_path/Tools/metric/milling/bull-endmills-metric"
"$nc_tools_path/Tools/metric/milling/endmills-metric"
"$nc_tools_path/Tools/metric/milling/facemills-metric"
"$nc_tools_path/Tools/metric/milling/mills-metric"
"$nc_tools_path/Tools/metric/milling/taper-ball-endmills-metric"
"$nc_tools_path/Tools/metric/milling/taper-endmills-metric"
"$nc_tools_path/Tools/metric/turning"
"$nc_tools_path/Tools/metric/turning/center_drills"
"$nc_tools_path/Tools/metric/turning/drills"
"$nc_tools_path/Tools/metric/turning/grooving"
"$nc_tools_path/Tools/metric/turning/mill_tools"
"$nc_tools_path/Tools/metric/turning/turning_tools"
"$nc_tools_path/Workcells"
"$nc_tools_path/Workcells/Haas_Machine"
